autoEmoticons:
  useEmojiSave: false
  expireTimeInSeconds: 259200
  confirmCount: 3
  replyRate: 0.05
  maxEmojiCount: 100
  maxEmojiSize: 10
  allowGroups: []
  getBotByQQ_targetQQArr: []
  sendCD: 299
  timeRestrictionEnabled: false
  activeStartTime: "08:00"
  activeEndTime: "23:00"
  replyDelay: { min: 1000, max: 240000 }

pokeConfig:
  enable: false
  reply_text_prob: 0.2
  reply_img_prob: 0.5
  mutepick_prob: 0
  mute_duration: 60
  word_list: "不要再戳了！\n救命啊，有变态>_<！！！\n你戳谁呢！你戳谁呢！！！o(´^｀)o\n不要再戳了！我真的要被你气死了！！！\n就你小子乱戳我，找打！"

emojiReaction:
  enable: false
  emojiId: "74"
  useSameEmoji: false
  reactToAllEmojis: true
  cooldown: 5
  onlyGroups: []
  globalEnabled: false
